version: '3.8'

services:
  app:
    image: your-spring-boot-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_APPLICATION_NAME=${APPLICATION_NAME}
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
