version: '3.8'

services:
  app:
    image: your-spring-boot-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${HIBERNATE_DDL_AUTO}
      - SPRING_JPA_DATABASE_PLATFORM=${HIBERNATE_DIALECT}
      - SPRING_JPA_SHOW_SQL=${SHOW_SQL}
      - SPRING_APPLICATION_NAME=${APPLICATION_NAME}
    env_file:
      - .env
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
