services:
  app:
    image: your-spring-boot-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres
      - SPRING_DATASOURCE_USERNAME=postgres.wdtlgkqggwmhicevhlek
      - SPRING_DATASOURCE_PASSWORD=emrah123
      - SPRING_APPLICATION_NAME=kahootcl

    networks:
      - backend_network



networks:
  backend_network:
    drive